Feature #43: Preparation OpenSource
  Start a new integration for SQLcipher and import files in new git
  repository that is created from the sqlcipher official git, branch v4.6.1
  Add our integration:
   - BUILD.gn to build in WebRTC,
   - android/* for Java support,
   - src/sqlite3.h
   - src/sqlite3.c

  Below is our git log history for the integration.

  commit 7efe32001da0cd3cd7e72356f13b3b4bbbcc056d
  Author: Stephane Carrez <Stephane.Carrez@gmail.com>
  Date:   Wed Jun 18 10:30:33 2025 +0200

    Feature #10: Adaptations WebRTC pour les engines

      Modified files:
        o BUILD.gn
          Update configuration to build for Linux as target.
        o android/net_sqlcipher_CursorWindow.cpp
        o android/net_sqlcipher_database_SQLiteCompiledSql.cpp
        o android/net_sqlcipher_database_SQLiteDatabase.cpp
        o android/net_sqlcipher_database_SQLiteProgram.cpp
        o android/net_sqlcipher_database_SQLiteQuery.cpp
        o android/net_sqlcipher_database_SQLiteStatement.cpp
          Add #pragma clang diagnostic ignored "-Wwritable-strings"

  commit 7c48653f900e22dfb5fdf51b5fa5f158935b23e3
  Author: Stephane Carrez <Stephane.Carrez@twin.life>
  Date:   Thu Mar 13 09:08:22 2025 +0100

    Feature #31: Intégration WebRTC 134

      Modified files:
        o src/sqlite3.c
          Add #pragma clang diagnostic ignored "-Wgnu-pointer-arith"
          to fix compilation issue.

  commit 7f19f6c7de128e8499eeaaf9397fbd06f43cef4a
  Merge: 2ebfcff d6ee800
  Author: Stephane Carrez <Stephane.Carrez@twin.life>
  Date:   Thu Feb 13 10:15:46 2025 +0100

    Merge branch 'sqlcipher/master' into twinlife-1.0/master

  commit d6ee800ba4c68b6441e8d4d3e4326e6ef3f46168
  Author: Stephane Carrez <Stephane.Carrez@twin.life>
  Date:   Thu Feb 13 09:39:17 2025 +0100

    Bug #3613: [sqlcipher] Integrate SQLCipher v4.6.1

      New files:
        o sqlite3.c
        o sqlite3.h
          Add amalgation files generated using the commands:
          $ ./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC"
          $ make sqlite3.c

      Deleted files:
        o remove build files

  commit 2ebfcff3408e7b4ceaa280143e8219c31382991d
  Author: Stephane Carrez <Stephane.Carrez@twin.life>
  Date:   Thu Feb 13 10:06:53 2025 +0100

    Feature #29: Integration SQLCipher v4.6.1

      Modified files:
        o src/sqlite3.c
          Update compilation for WebRTC.

      Deleted files:
        o sqlite3.c
        o sqlite3.h
          Drop old files.

  commit 8424b42b7b296e8f36bd8300d9c9c672300423b3
  Merge: e05223e 6145d6e
  Author: Stephane Carrez <Stephane.Carrez@twin.life>
  Date:   Thu Feb 13 09:39:58 2025 +0100

    Merge branch 'sqlcipher/master' into twinlife-1.0/master

  commit 6145d6eb0fa2cb889f83189bb0a3dc476b3827c1
  Author: Stephane Carrez <Stephane.Carrez@twin.life>
  Date:   Thu Feb 13 09:39:17 2025 +0100

    Bug #3613: [sqlcipher] Integrate SQLCipher v4.5.3

      New files:
        o sqlite3.c
        o sqlite3.h
          Add amalgation files generated using the commands:
          $ ./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC"
          $ make sqlite3.c

  commit e05223e047cc3f8d3f8a0fdfdda7f3bad2e47e28
  Merge: e3e2ee4 3ba3dfc
  Author: Stephane Carrez <Stephane.Carrez@twin.life>
  Date:   Thu Feb 13 09:35:27 2025 +0100

    Merge branch 'sqlcipher/master' into twinlife-1.0/master

  commit 3ba3dfc7cc53a8f31836c4e1860f6bbf666793c5
  Author: Stephane Carrez <Stephane.Carrez@twin.life>
  Date:   Thu Feb 13 09:34:14 2025 +0100

    Feature #3613: [sqlcipher] Integrate SQLCipher

       Integrate sqlcipher v4.6.1:

         git clone https://github.com/sqlcipher/sqlcipher.git
         cd sqlcipher
         git checkout v4.6.1

       In local repository (keep android files):
         cp -rp android ..
         rm -rf *
         cp -rp /..../sqlcipher/* .
         mv ../android .
         git add .
         git commit

  commit e3e2ee4022fb24ff87b29231997a906a78250dbc
  Author: Stephane Carrez <Stephane.Carrez@twin.life>
  Date:   Thu Apr 6 16:35:30 2023 +0200

    Intégration WebRTC 112

      Modified files:
        o src/sqlite3.c
          Don't compile with SQLITE_DEBUG

  commit c2a843c471d6d60633212605aea35aefa0d42c36
  Merge: f75afc2 84d34b4
  Author: Stephane Carrez <Stephane.Carrez@twin.life>
  Date:   Tue Apr 4 18:17:21 2023 +0200

    Merge branch 'sqlcipher/master' into twinlife-1.0/master

  commit 84d34b457ca578cbbbe332ac0465c414009e8e56
  Author: Stephane Carrez <Stephane.Carrez@twin.life>
  Date:   Tue Apr 4 18:16:50 2023 +0200

    Feature #3613: [sqlcipher] Integrate SQLCipher

      Modified files:
        o android/sqlcipher_loading.h
        o android/sqlite3_exception.h
          Moved from old src

  commit f75afc2cf17b71a0fbef739448adc1f62635bc88
  Author: Stephane Carrez <Stephane.Carrez@twin.life>
  Date:   Tue Apr 4 17:59:45 2023 +0200

    Intégration WebRTC 112

      Modified files:
        o BUILD.gn
          Update to build the SQLcipher library
        o android/net_sqlcipher_database_SQLiteDatabase.cpp
        o src/sqlite3.c
          Fix compilation issues

  commit eec42f259cc41da75bf053e2a39fc7bbe0df64dd
  Author: Stephane Carrez <Stephane.Carrez@twin.life>
  Date:   Tue Apr 4 14:31:36 2023 +0200

    Intégration WebRTC 112

      Modified files:
        o BUILD.gn
          Cleanup for WebRTC 112

  commit e786985e05d572a07703a5a1203a6fe4d8910a0c
  Merge: 5bf56d8 7726354
  Author: Stephane Carrez <Stephane.Carrez@twin.life>
  Date:   Thu Jan 12 23:54:20 2023 +0100

    Merge branch 'sqlcipher/master' into twinlife-1.0/master

  commit 772635459f0edefd83b05bad43937aea449f2bc9
  Author: Stephane Carrez <Stephane.Carrez@twin.life>
  Date:   Thu Jan 12 23:53:39 2023 +0100

    Feature #3613: [sqlcipher] Integrate SQLCipher

      New files:
        o android/CursorWindow.h
          Android specific file moved from src

  commit 5bf56d8bac98a18c2631eddb8e9ddd3b4f11ef08
  Merge: ea23502 5b330c1
  Author: Stephane Carrez <Stephane.Carrez@twin.life>
  Date:   Thu Jan 12 23:53:12 2023 +0100

    Merge branch 'sqlcipher/master' into twinlife-1.0/master

  commit 5b330c1a5af1f2a25f4cc2d63159b26be51f7f3b
  Author: Stephane Carrez <Stephane.Carrez@twin.life>
  Date:   Thu Jan 12 23:47:15 2023 +0100

    Bug #3613: [sqlcipher] Integrate SQLCipher v4.5.3

      New files:
        o sqlite3.c
        o sqlite3.h
          Add amalgation files generated using the commands:
          $ ./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC"
          $ make
        These files are identical to the same files obtained in the build process
        of android-database-sqlcipher project

  commit f595925bbf6742d3421a3298f46bd0318f4afa3a
  Author: Stephane Carrez <Stephane.Carrez@twin.life>
  Date:   Thu Jan 12 23:41:30 2023 +0100

    Feature #3613: [sqlcipher] Integrate SQLCipher

      Integrate sqlcipher v4.5.3:

        git clone https://github.com/sqlcipher/sqlcipher.git
        cd sqlcipher
        git checkout v4.5.3

      In local repository (keep android files):
        cp -rp android ..
        rm -rf *
        cp -rp /..../sqlcipher/* .
        mv ../android .
        git add .
        git commit

  commit 5d651400c153f4b349216015f70e449edc45d69d
  Author: Stephane Carrez <Stephane.Carrez@twin.life>
  Date:   Thu Jan 12 23:34:46 2023 +0100

    Feature #3613: [sqlcipher] Integrate SQLCipher

      Moved files:
        o src/CursorWindow.cpp -> android/CursorWindow.cpp
        o src/jni_elements.h -> android/jni_elements.h
        o src/jni_exception.cpp -> android/jni_exception.cpp
        o src/jni_exception.h -> android/jni_exception.h
        o src/log.h -> android/log.h
        o src/net_sqlcipher_CursorWindow.cpp -> android/net_sqlcipher_CursorWindow.cpp
        o src/net_sqlcipher_database_SQLiteCompiledSql.cpp -> android/net_sqlcipher_database_SQLiteCompiledSql.cpp
        o src/net_sqlcipher_database_SQLiteDatabase.cpp -> android/net_sqlcipher_database_SQLiteDatabase.cpp
        o src/net_sqlcipher_database_SQLiteProgram.cpp -> android/net_sqlcipher_database_SQLiteProgram.cpp
        o src/net_sqlcipher_database_SQLiteQuery.cpp -> android/net_sqlcipher_database_SQLiteQuery.cpp
        o src/net_sqlcipher_database_SQLiteStatement.cpp -> android/net_sqlcipher_database_SQLiteStatement.cpp
          Move Android/Java specific files to a separate directory to help the sqlcipher integration.

  commit ea23502a3b26984d3d66dad71dfd80644e169339
  Author: Stephane Carrez <Stephane.Carrez@gmail.com>
  Date:   Tue Oct 18 17:19:47 2022 +0200

    Feature #2: Intégration WebRTC 107

      Modified files:
        o src/sqlite3.c
          Fix compilation with llvm 16.0

  commit 7c9a327754c7b2a3c11fd7ab81b249a894c866df
  Author: Stephane Carrez <Stephane.Carrez@gmail.com>
  Date:   Tue Mar 8 09:27:11 2022 +0100

    Feature #4824: Synchronization with Google repository (WebRTC 100)

      Modified files:
        o src/sqlite3.c
          Fix compilation.

  commit 3f297a76d2a6f9c9e00c25a344f3ead9b3d7505b
  Author: Christian Jacquemot <Christian.Jacquemot@twinlife-systems.com>
  Date:   Fri Sep 17 07:50:17 2021 +0200

    Feature #4418: Synchronization with Google repository (WebRTC 95)

     Modified files:
      o src/sqlite3.c
        Remove unreachable break to fix error: 'break' will never be executed [-Werror,-Wunreachable-code-break]

  commit 8d3400eef6478d6afb17378aa4902d09d8e76d16
  Author: Christian Jacquemot <Christian.Jacquemot@twinlife-systems.com>
  Date:   Wed Aug 18 16:18:50 2021 +0200

    Feature #4324: Synchronization with Google repository (WebRTC 94)

     Modified files:
      o src/sqlite3.c
        Insert '__attribute__((fallthrough));' to correct unannotated fall-through between switch labels - WebRTC is compiled with -Werror,-Wimplicit-fallthrough options

  commit 35bcbe4e16dc41e6ff01a1608234bddfdba3ff8e
  Author: Christian Jacquemot <Christian.Jacquemot@twinlife-systems.com>
  Date:   Wed Nov 4 13:33:12 2020 +0100

    Feature #3613: [sqlcipher] Integrate SQLCipher

     Modified files:
      o BUILD.gn
        Add include_dirs
        Add CursorWindow.cpp, jni_exception.cpp, net_sqlcipher_CursorWindow.cpp, net_sqlcipher_database_SQLiteCompiledSql.cpp,
        net_sqlcipher_database_SQLiteDatabase.cpp, net_sqlcipher_database_SQLiteQuery.cpp, net_sqlcipher_database_SQLiteProgram.cpp,
        et_sqlcipher_database_SQLiteStatement.cpp in sources list
      o src/CursorWindow.cpp
      o src/CursorWindow.h
        Fix: error: comparison of integers of different signs: 'size_t'
         int32_t freeSpace() -> size_t freeSpace()
         uint32_t read_field_slot(int row, int column, field_slot_t * slot) ->
          uint32_t read_field_slot(uint32_t row, uint32_t column, field_slot_t * slot)
         row_slot_t * getRowSlot(int row) -> row_slot_t * getRowSlot(uint32_t row)
         field_slot_t * getFieldSlotWithCheck(int row, int column) ->
          field_slot_t * getFieldSlotWithCheck(uint32_t row, uint32_t column)
         field_slot_t * getFieldSlot(int row, int column) ->
          field_slot_t * getFieldSlot(uint32_t row, uint32_t column)
        Fix: error: extra ';' outside of a function is incompatible with C++98 [-Werror,-Wc++98-compat-extra-semi]
         }; // namespace sqlcipher -> } // namespace sqlcipher
      o src/net_sqlcipher_CursorWindow.cpp
        Fix: error: unused variable 'size' [-Werror,-Wunused-variable]
        Fix: error: unused variable 'data' [-Werror,-Wunused-variable]
        Fix: error: unused variable 'i' [-Werror,-Wunused-variable]
      o src/net_sqlcipher_database_SQLiteCompiledSql.cpp
        Fix: error: unused variable 'err' [-Werror,-Wunused-variable]
      o src/net_sqlcipher_database_SQLiteDatabase.cpp
        Fix: error: unused variable 'index' [-Werror,-Wunused-variable]
        Fix: error: unused variable 'idx' [-Werror,-Wunused-variable]
        Fix: error: unused variable 'releaseElements' [-Werror,-Wunused-variable]
        Fix: error: unused variable 'd' [-Werror,-Wunused-variable]
        Rename JNI_OnLoad() JNI_OnLoad1() to avoid conflict whith WebRTC implementation of JNI_OnLoad()
      o src/net_sqlcipher_database_SQLiteProgram.cpp
        Fix: unused variable 'sql' [-Werror,-Wunused-variable]
        Fix: unused variable 'sqlLen' [-Werror,-Wunused-variable]
        Fix: error: unused function 'native_compile' [-Werror,-Wunused-function]
        Fix: error: unused function 'native_finalize' [-Werror,-Wunused-function]
      o src/net_sqlcipher_database_SQLiteQuery.cpp
        Fix: unused variable 'boundParams' [-Werror,-Wunused-variable]

  commit 4bc805ac145a8deac5b3d0ab3c795d58af21d985
  Merge: 51fcbd3 919011f
  Author: Christian Jacquemot <Christian.Jacquemot@twinlife-systems.com>
  Date:   Wed Nov 4 11:44:16 2020 +0100

    Merge branch 'sqlcipher/master' into twinlife-1.0/master

  commit 919011f1967a37ad20226983403f144488c55268
  Author: Christian Jacquemot <Christian.Jacquemot@twinlife-systems.com>
  Date:   Wed Nov 4 08:22:04 2020 +0100

    Feature #3613: [sqlcipher] Integrate SQLCipher

     New files:
      o src/CursorWindow.cpp
      o src/CursorWindow.h
      o src/jni_elements.h
      o src/jni_exception.cpp
      o src/jni_exception.h
      o src/log.h
      o src/net_sqlcipher_CursorWindow.cpp
      o src/net_sqlcipher_database_SQLiteCompiledSql.cpp
      o src/net_sqlcipher_database_SQLiteDatabase.cpp
      o src/net_sqlcipher_database_SQLiteProgram.cpp
      o src/net_sqlcipher_database_SQLiteQuery.cpp
      o src/net_sqlcipher_database_SQLiteStatement.cpp
      o src/sqlcipher_loading.h
      o src/sqlite3_exception.h
        JNI interface implementation based on https://github.com/sqlcipher/android-database-sqlcipher.git
        v4.4.0

  commit 5093ec4a1cec4f68e95ff24466cbb997b4b57f94
  Author: Christian Jacquemot <Christian.Jacquemot@twinlife-systems.com>
  Date:   Wed Nov 4 08:06:31 2020 +0100

    Bug #3613: [sqlcipher] Integrate SQLCipher

     Renamed files:
      o sqlite3.c -> src/sqlite3.c
      o sqlite3.h -> src/sqlite3.h
        Move amalgation files into src directory

  commit 51fcbd3716ee638883ae1f3e2797a7526ffeec90
  Author: Christian Jacquemot <Christian.Jacquemot@twinlife-systems.com>
  Date:   Tue Nov 3 08:02:14 2020 +0100

    Bug #3613: [sqlcipher] Integrate SQLCipher

     Modified files:
      o sqlite3.c
        Fix compilation errors detect by the WebRTC compiler options
        Use #ifdef instead of #if - options -Werror,-Wundef
        Add missing void in sqlcipher_version() prototype - options -Werror,-Wstrict-prototypes
        Remove sqlite3PagerState() method - options -Werror,-Wunused-function
        Remove unreachable-code code options: -Werror,-Wunreachable-code
         if( REOPEN_AS_MEMDB(db) ){ ... }
        Add missing int cast options: -Werror,-Wsign-compare
         for(i=0, iByte=0; i<sizeof(zBuf)*2 && sqlite3Isxdigit(zRight[i]); i++){ -->
         for(i=0, iByte=0; i<(int)sizeof(zBuf)*2 && sqlite3Isxdigit(zRight[i]); i++){
         for(i=0, iByte=0; i<sizeof(zDecoded)*2 && sqlite3Isxdigit(zKey[i]); i++){ -->
         for(i=0, iByte=0; i<(int)sizeof(zDecoded)*2 && sqlite3Isxdigit(zKey[i]); i++){
        Move variable definition outside switch() -Werror,-Wunreachable-code
         YYMINORTYPE yylhsminor;
         fts5YYMINORTYPE fts5yylhsminor;

     New files:
      o BUILD.gn
        Compilation configuration based on compiler options used in the compilation of
        android-database-sqlcipher

  commit d971cc636cf208cc54adb68ebf39979b6f4b7f5f
  Author: Christian Jacquemot <Christian.Jacquemot@twinlife-systems.com>
  Date:   Tue Nov 3 07:53:08 2020 +0100

    Bug #3613: [sqlcipher] Integrate SQLCipher

     New files:
      o sqlite3.c
      o sqlite3.h
        Add amalgation files generated using the commands:
         $ ./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC"
         $ make
        These files are identical to the same files obtained in the build process
        of android-database-sqlcipher project

  commit c9a43fc4865cd1402d79a7cf145684cf074ad754
  Author: Christian Jacquemot <Christian.Jacquemot@twinlife-systems.com>
  Date:   Mon Nov 2 07:42:11 2020 +0100

    Initial version https://github.com/sqlcipher/sqlcipher.git v4.4.0